export const Trait = {
	"Backgrounds":{
		"Baby Pink" : "5.5",
		"Black" : "8",
		"Blue" : "8",
		"BluePurpleGradient" : "3",
		"Green" : "8",
		"Grey" : "12",
		"Pastel Blue" : "6",
		"Pastel Purple" : "5",
		"Pastel Yellow" : "5",
		"Pink" : "8",
		"PinkPurpleGradient" : "3",
		"Purple" : "8",
		"Red" : "8",
		"RedOrangeGradient" : "3",
		"Space" : "0.5",
		"Yellow" :"8",
		"Lightning" : "1"
	},
	"Chains" : {
		"Barbed Wire" : "6.2",
		"Cross" : "5",
		"Diamond Chain" : "4",
		"Double" : "5",
		"Gangster" : "5",
		"Gold" : "6",
		"Iridescent Barbed Wire" : "0.1",
		"Iridescent Chain" : "0.5",
		"Monkeys" : "1",
		"Planet" : "8",
		"Rainbow" : "6",
		"Sea Shell" : "4",
		"Shark Tooth" : "3",
		"Space Pass" : "1",
		"Chrome Cuban" : "5",
		"Cuban" : "10",
		"Gold Barbed Wire" : "1.2",
		"Rabbits Foot" : "5",
		"NEAR" : "3",
		"Rainbow Cuban" : "5",
		"Rope" : "10",
		"Spiked" : "6"
	},
	"Eyes" : {
		"Black"	: "10",
		"Black Hole": "1",
		"Bloodshot" : "8",
		"Crying" : "9",
		"Diamond" : "3",
		"Evil" : "10.3",
		"Hypno" : "8",
		"NEAR" : "1",
		"Normal" : "15",
		"Pop out" : "8",
		"Raised eyebrow" : "8",
		"Zombie" : "5",
		"Cyborg" : "0.2",
		"Eye Patch" : "5",
		"Futuristic Shades" : "0.4",
		"Lennon Shades" : "0.1",
		"Shades" : "8"
	},
	"Fur" : {
		"Blue Camo" : "5",
		"Blue" : "8",
		"Blue Zombie" : "5",
		"Camo Zombie" : "3",
		"Chrome" : "0.15",
		"Gold" : "3",
		"Green" : "12",
		"Green Zombie" : "3",
		"Grey Camo" : "3",
		"Iridescent" : "0.1",
		"Pink" : "5",
		"Pink Zombie" : "2",
		"Purple" : "10",
		"Rainbow" : "5",
		"Red Camo" : "3",
		"Red" : "7",
		"Red Zombie" : "5",
		"Space" : "1",
		"Trippy Zombie" : "0.05",
		"White" : "10",
		"Yellow" : "8",
		"Dark Green Zombie" : "0.25",
		"Fire" : "1.45"
	},
	"Helmets" : {
		"Apocalypse" : "2.5",
		"Black" : "4",
		"Blue" : "7",
		"Camo" : "3.3",
		"Chrome" : "0.6",
		"Gold" : "3",
		"Green" : "10",
		"Iridescent" : "0.1",
		"Pink" : "9",
		"Purple" : "8",
		"Racing" : "3",
		"Rainbow" : "6",
		"Red" : "10",
		"Ronin": "1",
		"White" : "10",
		"Christmas" : "1",
		"Cowboy" : "5",
		"Cyborg" : "4",
		"Halloween" : "1.3",
		"Navy Football" : "1",
		"Ninja" : "5",
		"Pirate" : "0.2",
		"Red Football" : "5"
	},
	"Mouths" : {
		"Braces" : "8",
		"Chrome Fangs" : "2",
		"Fangs" : "6",
		"Gold Fangs" : "3",
		"Missing Teeth" : "9",
		"Normal" : "8",
		"Rainbow Grill" : "3",
		"Shocked" : "9",
		"Smile" : "11",
		"Sulking" : "9",
		"Tongue Out" : "4",
		"Zipped" : "8",
		"Zombie" : "6",
		"Drool" : "10",
		"Sabertooth" : "4"
	},
	"Spacesuits" : {
		"Apocalypse" : "1.25",
		"Blue Camo" : "4",
		"Blue" : "13",
		"Chrome" : "1",
		"Green" : "13",
		"Grey Camo" : "3",
		"Iridescent"  : "0.25",
		"Normal" : "15",
		"Pink" : "8",
		"Purple" : "8",
		"Rainbow" : "3",
		"Red Camo" : "4",
		"Red" : "13.5",
		"Ronin": "1",
		"Yellow" : "12"
	},
	"Visors" : {
		"Blue Tint" : "8",
		"Camo" : "6",
		"Chrome" : "0.5",
		"Clear" : "14",
		"Cracked" : "10",
		"Dirty" : "8",
		"Graffiti" : "4",
		"Iridescent" : "0.2",
		"Pink" : "9",
		"Purple" : "8",
		"Racing" : "5",
		"Rainbow" : "4.4",
		"Black Tint" : "12",
		"Yellow Tint" : "8",
		"Halloween" : "0.4",
		"Ninja" : "2",
		"Christmas" : "0.5"
	}
}